services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - DATABASE_TYPE=sqlite
      - DATABASE_URL=/app/data/production.db
      - PORT=3000
      - HOST=0.0.0.0
    volumes:
      - app_data:/app/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # PostgreSQL database (optional - uncomment if using PostgreSQL)
  # postgres:
  #   image: postgres:15-alpine
  #   environment:
  #     POSTGRES_DB: elysia_boilerplate
  #     POSTGRES_USER: postgres
  #     POSTGRES_PASSWORD: password
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data
  #   ports:
  #     - "5432:5432"
  #   restart: unless-stopped

volumes:
  app_data:
  # postgres_data: